audio_quality: Fix for 64-bit compatibility
when compile with the aarch64 bit toolchain, it will report errors like this:
  error: call of overloaded 'Value(long long int&)' is ambiguous

here changed the value to int64_t type instead of long long type to make it call
TaskCase::Value::Value(int64_t) constructor explicitly

Change-Id: I0e54d9ab6b686873e7063b4e8d85880eddc3b38b
Signed-off-by: Yongqin Liu <yongqin.liu@linaro.org>