More tests.
Now testing pretty much all of the UI widgets.
Exception: ActionBar which requires some hackery.
Now also doing portrait and landscape tests
because some things (Dialogs, mostly) will
be different based upon orientation.
Also added some mdpi versions of the masters.

Change-Id: Ib061e18ad563cf767070adb69329dde499f27331