cts: define mcpu=generic for 32-bit ARM builds
* ARMv8 does not support SWP instructions, so this test is to be
  sure that SWP is emulated. Without this commit, the following
  error is generated on ARMv8 while compiling the CPU Instructions
  test:

error: instruction requires: armv7 or earlier
    asm volatile ( "swp r0, r0, [%0]" : "+r"(ptr) : : "r0" );

* Thank you to Alistair Strachan for finding the problem and
   solution.

Change-Id: Ifd6a29373a387f44dfe06a88b72cc22b46516cfa