Revert "[RenderScript] Add CTS correctness tests for L3 BLAS Intrinsic"
error: code too large, moving to native one

This reverts commit 8f77481ea4c5add5fac3925db731d340eb447db2.

Change-Id: I43a76f5808f9f5bfcca226f8de1b78d295297891