Fix MediaRandomTest watchdog affecting other tests
Bug 6971082

MediaRandomTest fails when the media server crashes, but the watchdog
kicks in later during another test and causes that test to fail.
Thus, make sure to end the watchdog after each test.

10-08 14:41:56.629  2274  2292 I TestRunner: started:
testOnInfoListener(android.media.cts.MediaRecorderTest)
10-08 14:41:59.182  2274  8725 E AndroidRuntime:
junit.framework.AssertionFailedError: Action 11 Param 581451 waited over
5000 ms
10-08 14:41:59.182  2274  8725 E AndroidRuntime:    at
junit.framework.Assert.fail(Assert.java:50)
10-08 14:41:59.182  2274  8725 E AndroidRuntime:    at
android.media.cts.MediaRandomTest$Watchdog.run(MediaRandomTest.java:141)

Change-Id: I1f956f2c0ab71ee3790b42ff2931b9119878829d