Revert "Cleanup vroot test and fix false positive."
code compiles on klp-dev but not on jb-dev. *sigh*

In file included from cts/tests/tests/security/jni/android_security_cts_NativeCodeTest.cpp:31:0:
bionic/libc/kernel/common/linux/sysctl.h:37:43: error: expected unqualified-id before '[' token
make: *** [out/target/product/generic/obj/SHARED_LIBRARIES/libctssecurity_jni_intermediates/android_security_cts_NativeCodeTest.o] Error 1

This reverts commit 65809bca4f0e2381b0a97a1db5f8166a19ca0d46.

Bug: 15408470
Change-Id: I35ac2f25e5a00c21628a1139a7426ca0f046d6d4